image: ilyasemenov/gitlab-ci-git-push

variables:
  GIT_DEPTH: 1000

stages:
  - production

production:
  stage: production
  environment:
    name: production
  only:
    - main
  script:
    - git-push $DOKKU_URL
